function createEmptyIR(title = 'API', version = '1.0.0') {
    return {
        info: {
            title,
            version,
            description: 'Generated by SpringBoot2Postman',
        },
        servers: [
            {
                url: 'http://localhost:8080',
                description: 'Local development server',
            },
        ],
        endpoints: [],
        schemas: {},
    };
}

function createEndpoint(method, path, name) {
    return {
        id: `${method.toLowerCase()}_${path.replace(/[^a-zA-Z0-9]/g, '_')}`,
        name,
        method,
        path,
        tags: [],
        parameters: {
            path: [],
            query: [],
            header: [],
        },
        responses: [
            {
                status: 200,
                description: 'Successful response',
                contentType: 'application/json',
            },
        ],
    };
}

function createParameter(name, javaType, inLocation, required = false) {
    return {
        name,
        javaType,
        jsonType: 'string',
        required,
        in: inLocation,
    };
}

function createRequestBody(javaType, required = true) {
    return {
        required,
        contentType: 'application/json',
        schema: {
            $ref: `#/components/schemas/${javaType}`,
        },
    };
}

function addEndpoint(ir, endpoint) {
    return {
        ...ir,
        endpoints: [...ir.endpoints, endpoint],
    };
}

function addSchema(ir, name, schema) {
    return {
        ...ir,
        schemas: { ...ir.schemas, [name]: schema },
    };
}

function setServerUrl(ir, url) {
    const servers = [...ir.servers];
    servers[0] = { ...servers[0], url };
    return { ...ir, servers };
}

module.exports = {
    createEmptyIR,
    createEndpoint,
    createParameter,
    createRequestBody,
    addEndpoint,
    addSchema,
    setServerUrl,
};
